/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.axa.glf.masterdata.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Vehicle_Catalogue service. Represents a row in the &quot;glf_Vehicle_Catalogue&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.axa.glf.masterdata.model.impl.Vehicle_CatalogueModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.axa.glf.masterdata.model.impl.Vehicle_CatalogueImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Vehicle_Catalogue
 * @see com.axa.glf.masterdata.model.impl.Vehicle_CatalogueImpl
 * @see com.axa.glf.masterdata.model.impl.Vehicle_CatalogueModelImpl
 * @generated
 */
@ProviderType
public interface Vehicle_CatalogueModel extends BaseModel<Vehicle_Catalogue>,
	GroupedModel, ShardedModel, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vehicle_ catalogue model instance should use the {@link Vehicle_Catalogue} interface instead.
	 */

	/**
	 * Returns the primary key of this vehicle_ catalogue.
	 *
	 * @return the primary key of this vehicle_ catalogue
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vehicle_ catalogue.
	 *
	 * @param primaryKey the primary key of this vehicle_ catalogue
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this vehicle_ catalogue.
	 *
	 * @return the uuid of this vehicle_ catalogue
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this vehicle_ catalogue.
	 *
	 * @param uuid the uuid of this vehicle_ catalogue
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the vehicle ID of this vehicle_ catalogue.
	 *
	 * @return the vehicle ID of this vehicle_ catalogue
	 */
	public long getVehicleId();

	/**
	 * Sets the vehicle ID of this vehicle_ catalogue.
	 *
	 * @param vehicleId the vehicle ID of this vehicle_ catalogue
	 */
	public void setVehicleId(long vehicleId);

	/**
	 * Returns the group ID of this vehicle_ catalogue.
	 *
	 * @return the group ID of this vehicle_ catalogue
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this vehicle_ catalogue.
	 *
	 * @param groupId the group ID of this vehicle_ catalogue
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this vehicle_ catalogue.
	 *
	 * @return the company ID of this vehicle_ catalogue
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this vehicle_ catalogue.
	 *
	 * @param companyId the company ID of this vehicle_ catalogue
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this vehicle_ catalogue.
	 *
	 * @return the user ID of this vehicle_ catalogue
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this vehicle_ catalogue.
	 *
	 * @param userId the user ID of this vehicle_ catalogue
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this vehicle_ catalogue.
	 *
	 * @return the user uuid of this vehicle_ catalogue
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this vehicle_ catalogue.
	 *
	 * @param userUuid the user uuid of this vehicle_ catalogue
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this vehicle_ catalogue.
	 *
	 * @return the user name of this vehicle_ catalogue
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this vehicle_ catalogue.
	 *
	 * @param userName the user name of this vehicle_ catalogue
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this vehicle_ catalogue.
	 *
	 * @return the create date of this vehicle_ catalogue
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this vehicle_ catalogue.
	 *
	 * @param createDate the create date of this vehicle_ catalogue
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this vehicle_ catalogue.
	 *
	 * @return the modified date of this vehicle_ catalogue
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this vehicle_ catalogue.
	 *
	 * @param modifiedDate the modified date of this vehicle_ catalogue
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the automobile_cat_code of this vehicle_ catalogue.
	 *
	 * @return the automobile_cat_code of this vehicle_ catalogue
	 */
	@AutoEscape
	public String getAutomobile_cat_code();

	/**
	 * Sets the automobile_cat_code of this vehicle_ catalogue.
	 *
	 * @param automobile_cat_code the automobile_cat_code of this vehicle_ catalogue
	 */
	public void setAutomobile_cat_code(String automobile_cat_code);

	/**
	 * Returns the automobile_maker_code of this vehicle_ catalogue.
	 *
	 * @return the automobile_maker_code of this vehicle_ catalogue
	 */
	@AutoEscape
	public String getAutomobile_maker_code();

	/**
	 * Sets the automobile_maker_code of this vehicle_ catalogue.
	 *
	 * @param automobile_maker_code the automobile_maker_code of this vehicle_ catalogue
	 */
	public void setAutomobile_maker_code(String automobile_maker_code);

	/**
	 * Returns the automobile_maker_name of this vehicle_ catalogue.
	 *
	 * @return the automobile_maker_name of this vehicle_ catalogue
	 */
	@AutoEscape
	public String getAutomobile_maker_name();

	/**
	 * Sets the automobile_maker_name of this vehicle_ catalogue.
	 *
	 * @param automobile_maker_name the automobile_maker_name of this vehicle_ catalogue
	 */
	public void setAutomobile_maker_name(String automobile_maker_name);

	/**
	 * Returns the automobile_model_code of this vehicle_ catalogue.
	 *
	 * @return the automobile_model_code of this vehicle_ catalogue
	 */
	@AutoEscape
	public String getAutomobile_model_code();

	/**
	 * Sets the automobile_model_code of this vehicle_ catalogue.
	 *
	 * @param automobile_model_code the automobile_model_code of this vehicle_ catalogue
	 */
	public void setAutomobile_model_code(String automobile_model_code);

	/**
	 * Returns the automobile_model_name of this vehicle_ catalogue.
	 *
	 * @return the automobile_model_name of this vehicle_ catalogue
	 */
	@AutoEscape
	public String getAutomobile_model_name();

	/**
	 * Sets the automobile_model_name of this vehicle_ catalogue.
	 *
	 * @param automobile_model_name the automobile_model_name of this vehicle_ catalogue
	 */
	public void setAutomobile_model_name(String automobile_model_name);

	/**
	 * Returns the automobile_version_code of this vehicle_ catalogue.
	 *
	 * @return the automobile_version_code of this vehicle_ catalogue
	 */
	@AutoEscape
	public String getAutomobile_version_code();

	/**
	 * Sets the automobile_version_code of this vehicle_ catalogue.
	 *
	 * @param automobile_version_code the automobile_version_code of this vehicle_ catalogue
	 */
	public void setAutomobile_version_code(String automobile_version_code);

	/**
	 * Returns the automobile_version_name of this vehicle_ catalogue.
	 *
	 * @return the automobile_version_name of this vehicle_ catalogue
	 */
	@AutoEscape
	public String getAutomobile_version_name();

	/**
	 * Sets the automobile_version_name of this vehicle_ catalogue.
	 *
	 * @param automobile_version_name the automobile_version_name of this vehicle_ catalogue
	 */
	public void setAutomobile_version_name(String automobile_version_name);

	/**
	 * Returns the automobile_sub_type_name of this vehicle_ catalogue.
	 *
	 * @return the automobile_sub_type_name of this vehicle_ catalogue
	 */
	@AutoEscape
	public String getAutomobile_sub_type_name();

	/**
	 * Sets the automobile_sub_type_name of this vehicle_ catalogue.
	 *
	 * @param automobile_sub_type_name the automobile_sub_type_name of this vehicle_ catalogue
	 */
	public void setAutomobile_sub_type_name(String automobile_sub_type_name);

	/**
	 * Returns the automobile_usage_type_name of this vehicle_ catalogue.
	 *
	 * @return the automobile_usage_type_name of this vehicle_ catalogue
	 */
	@AutoEscape
	public String getAutomobile_usage_type_name();

	/**
	 * Sets the automobile_usage_type_name of this vehicle_ catalogue.
	 *
	 * @param automobile_usage_type_name the automobile_usage_type_name of this vehicle_ catalogue
	 */
	public void setAutomobile_usage_type_name(String automobile_usage_type_name);

	/**
	 * Returns the automobile_body_type_name of this vehicle_ catalogue.
	 *
	 * @return the automobile_body_type_name of this vehicle_ catalogue
	 */
	@AutoEscape
	public String getAutomobile_body_type_name();

	/**
	 * Sets the automobile_body_type_name of this vehicle_ catalogue.
	 *
	 * @param automobile_body_type_name the automobile_body_type_name of this vehicle_ catalogue
	 */
	public void setAutomobile_body_type_name(String automobile_body_type_name);

	/**
	 * Returns the automobile_body_type_desc of this vehicle_ catalogue.
	 *
	 * @return the automobile_body_type_desc of this vehicle_ catalogue
	 */
	@AutoEscape
	public String getAutomobile_body_type_desc();

	/**
	 * Sets the automobile_body_type_desc of this vehicle_ catalogue.
	 *
	 * @param automobile_body_type_desc the automobile_body_type_desc of this vehicle_ catalogue
	 */
	public void setAutomobile_body_type_desc(String automobile_body_type_desc);

	/**
	 * Returns the automobile_fuel_type_name of this vehicle_ catalogue.
	 *
	 * @return the automobile_fuel_type_name of this vehicle_ catalogue
	 */
	@AutoEscape
	public String getAutomobile_fuel_type_name();

	/**
	 * Sets the automobile_fuel_type_name of this vehicle_ catalogue.
	 *
	 * @param automobile_fuel_type_name the automobile_fuel_type_name of this vehicle_ catalogue
	 */
	public void setAutomobile_fuel_type_name(String automobile_fuel_type_name);

	/**
	 * Returns the automobile_type_name of this vehicle_ catalogue.
	 *
	 * @return the automobile_type_name of this vehicle_ catalogue
	 */
	@AutoEscape
	public String getAutomobile_type_name();

	/**
	 * Sets the automobile_type_name of this vehicle_ catalogue.
	 *
	 * @param automobile_type_name the automobile_type_name of this vehicle_ catalogue
	 */
	public void setAutomobile_type_name(String automobile_type_name);

	/**
	 * Returns the power of this vehicle_ catalogue.
	 *
	 * @return the power of this vehicle_ catalogue
	 */
	@AutoEscape
	public String getPower();

	/**
	 * Sets the power of this vehicle_ catalogue.
	 *
	 * @param power the power of this vehicle_ catalogue
	 */
	public void setPower(String power);

	/**
	 * Returns the width of this vehicle_ catalogue.
	 *
	 * @return the width of this vehicle_ catalogue
	 */
	@AutoEscape
	public String getWidth();

	/**
	 * Sets the width of this vehicle_ catalogue.
	 *
	 * @param width the width of this vehicle_ catalogue
	 */
	public void setWidth(String width);

	/**
	 * Returns the surface of this vehicle_ catalogue.
	 *
	 * @return the surface of this vehicle_ catalogue
	 */
	@AutoEscape
	public String getSurface();

	/**
	 * Sets the surface of this vehicle_ catalogue.
	 *
	 * @param surface the surface of this vehicle_ catalogue
	 */
	public void setSurface(String surface);

	/**
	 * Returns the weight of this vehicle_ catalogue.
	 *
	 * @return the weight of this vehicle_ catalogue
	 */
	@AutoEscape
	public String getWeight();

	/**
	 * Sets the weight of this vehicle_ catalogue.
	 *
	 * @param weight the weight of this vehicle_ catalogue
	 */
	public void setWeight(String weight);

	/**
	 * Returns the vehicle_value of this vehicle_ catalogue.
	 *
	 * @return the vehicle_value of this vehicle_ catalogue
	 */
	@AutoEscape
	public String getVehicle_value();

	/**
	 * Sets the vehicle_value of this vehicle_ catalogue.
	 *
	 * @param vehicle_value the vehicle_value of this vehicle_ catalogue
	 */
	public void setVehicle_value(String vehicle_value);

	/**
	 * Returns the engine_cc of this vehicle_ catalogue.
	 *
	 * @return the engine_cc of this vehicle_ catalogue
	 */
	@AutoEscape
	public String getEngine_cc();

	/**
	 * Sets the engine_cc of this vehicle_ catalogue.
	 *
	 * @param engine_cc the engine_cc of this vehicle_ catalogue
	 */
	public void setEngine_cc(String engine_cc);

	/**
	 * Returns the rate_category of this vehicle_ catalogue.
	 *
	 * @return the rate_category of this vehicle_ catalogue
	 */
	@AutoEscape
	public String getRate_category();

	/**
	 * Sets the rate_category of this vehicle_ catalogue.
	 *
	 * @param rate_category the rate_category of this vehicle_ catalogue
	 */
	public void setRate_category(String rate_category);

	/**
	 * Returns the doors of this vehicle_ catalogue.
	 *
	 * @return the doors of this vehicle_ catalogue
	 */
	@AutoEscape
	public String getDoors();

	/**
	 * Sets the doors of this vehicle_ catalogue.
	 *
	 * @param doors the doors of this vehicle_ catalogue
	 */
	public void setDoors(String doors);

	/**
	 * Returns the allowed of this vehicle_ catalogue.
	 *
	 * @return the allowed of this vehicle_ catalogue
	 */
	@AutoEscape
	public String getAllowed();

	/**
	 * Sets the allowed of this vehicle_ catalogue.
	 *
	 * @param allowed the allowed of this vehicle_ catalogue
	 */
	public void setAllowed(String allowed);

	/**
	 * Returns the no_of_cylinder of this vehicle_ catalogue.
	 *
	 * @return the no_of_cylinder of this vehicle_ catalogue
	 */
	@AutoEscape
	public String getNo_of_cylinder();

	/**
	 * Sets the no_of_cylinder of this vehicle_ catalogue.
	 *
	 * @param no_of_cylinder the no_of_cylinder of this vehicle_ catalogue
	 */
	public void setNo_of_cylinder(String no_of_cylinder);

	/**
	 * Returns the restricted of this vehicle_ catalogue.
	 *
	 * @return the restricted of this vehicle_ catalogue
	 */
	@AutoEscape
	public String getRestricted();

	/**
	 * Sets the restricted of this vehicle_ catalogue.
	 *
	 * @param restricted the restricted of this vehicle_ catalogue
	 */
	public void setRestricted(String restricted);

	/**
	 * Returns the no_of_seats of this vehicle_ catalogue.
	 *
	 * @return the no_of_seats of this vehicle_ catalogue
	 */
	@AutoEscape
	public String getNo_of_seats();

	/**
	 * Sets the no_of_seats of this vehicle_ catalogue.
	 *
	 * @param no_of_seats the no_of_seats of this vehicle_ catalogue
	 */
	public void setNo_of_seats(String no_of_seats);

	/**
	 * Returns the engine_type of this vehicle_ catalogue.
	 *
	 * @return the engine_type of this vehicle_ catalogue
	 */
	@AutoEscape
	public String getEngine_type();

	/**
	 * Sets the engine_type of this vehicle_ catalogue.
	 *
	 * @param engine_type the engine_type of this vehicle_ catalogue
	 */
	public void setEngine_type(String engine_type);

	/**
	 * Returns the transmission_type of this vehicle_ catalogue.
	 *
	 * @return the transmission_type of this vehicle_ catalogue
	 */
	@AutoEscape
	public String getTransmission_type();

	/**
	 * Sets the transmission_type of this vehicle_ catalogue.
	 *
	 * @param transmission_type the transmission_type of this vehicle_ catalogue
	 */
	public void setTransmission_type(String transmission_type);

	/**
	 * Returns the no_of_gears of this vehicle_ catalogue.
	 *
	 * @return the no_of_gears of this vehicle_ catalogue
	 */
	@AutoEscape
	public String getNo_of_gears();

	/**
	 * Sets the no_of_gears of this vehicle_ catalogue.
	 *
	 * @param no_of_gears the no_of_gears of this vehicle_ catalogue
	 */
	public void setNo_of_gears(String no_of_gears);

	/**
	 * Returns the final_drive of this vehicle_ catalogue.
	 *
	 * @return the final_drive of this vehicle_ catalogue
	 */
	@AutoEscape
	public String getFinal_drive();

	/**
	 * Sets the final_drive of this vehicle_ catalogue.
	 *
	 * @param final_drive the final_drive of this vehicle_ catalogue
	 */
	public void setFinal_drive(String final_drive);

	/**
	 * Returns the no_of_axels of this vehicle_ catalogue.
	 *
	 * @return the no_of_axels of this vehicle_ catalogue
	 */
	@AutoEscape
	public String getNo_of_axels();

	/**
	 * Sets the no_of_axels of this vehicle_ catalogue.
	 *
	 * @param no_of_axels the no_of_axels of this vehicle_ catalogue
	 */
	public void setNo_of_axels(String no_of_axels);

	/**
	 * Returns the lower_threshold of this vehicle_ catalogue.
	 *
	 * @return the lower_threshold of this vehicle_ catalogue
	 */
	@AutoEscape
	public String getLower_threshold();

	/**
	 * Sets the lower_threshold of this vehicle_ catalogue.
	 *
	 * @param lower_threshold the lower_threshold of this vehicle_ catalogue
	 */
	public void setLower_threshold(String lower_threshold);

	/**
	 * Returns the upper_threshold of this vehicle_ catalogue.
	 *
	 * @return the upper_threshold of this vehicle_ catalogue
	 */
	@AutoEscape
	public String getUpper_threshold();

	/**
	 * Sets the upper_threshold of this vehicle_ catalogue.
	 *
	 * @param upper_threshold the upper_threshold of this vehicle_ catalogue
	 */
	public void setUpper_threshold(String upper_threshold);

	/**
	 * Returns the depreciation_flat of this vehicle_ catalogue.
	 *
	 * @return the depreciation_flat of this vehicle_ catalogue
	 */
	@AutoEscape
	public String getDepreciation_flat();

	/**
	 * Sets the depreciation_flat of this vehicle_ catalogue.
	 *
	 * @param depreciation_flat the depreciation_flat of this vehicle_ catalogue
	 */
	public void setDepreciation_flat(String depreciation_flat);

	/**
	 * Returns the value of this vehicle_ catalogue.
	 *
	 * @return the value of this vehicle_ catalogue
	 */
	@AutoEscape
	public String getValue();

	/**
	 * Sets the value of this vehicle_ catalogue.
	 *
	 * @param value the value of this vehicle_ catalogue
	 */
	public void setValue(String value);

	/**
	 * Returns the _1st_yr_dep_per of this vehicle_ catalogue.
	 *
	 * @return the _1st_yr_dep_per of this vehicle_ catalogue
	 */
	@AutoEscape
	public String get_1st_yr_dep_per();

	/**
	 * Sets the _1st_yr_dep_per of this vehicle_ catalogue.
	 *
	 * @param _1st_yr_dep_per the _1st_yr_dep_per of this vehicle_ catalogue
	 */
	public void set_1st_yr_dep_per(String _1st_yr_dep_per);

	/**
	 * Returns the _2nd_yr_dep_per of this vehicle_ catalogue.
	 *
	 * @return the _2nd_yr_dep_per of this vehicle_ catalogue
	 */
	@AutoEscape
	public String get_2nd_yr_dep_per();

	/**
	 * Sets the _2nd_yr_dep_per of this vehicle_ catalogue.
	 *
	 * @param _2nd_yr_dep_per the _2nd_yr_dep_per of this vehicle_ catalogue
	 */
	public void set_2nd_yr_dep_per(String _2nd_yr_dep_per);

	/**
	 * Returns the _3rd_yr_dep_per of this vehicle_ catalogue.
	 *
	 * @return the _3rd_yr_dep_per of this vehicle_ catalogue
	 */
	@AutoEscape
	public String get_3rd_yr_dep_per();

	/**
	 * Sets the _3rd_yr_dep_per of this vehicle_ catalogue.
	 *
	 * @param _3rd_yr_dep_per the _3rd_yr_dep_per of this vehicle_ catalogue
	 */
	public void set_3rd_yr_dep_per(String _3rd_yr_dep_per);

	/**
	 * Returns the _4th_yr_dep_per of this vehicle_ catalogue.
	 *
	 * @return the _4th_yr_dep_per of this vehicle_ catalogue
	 */
	@AutoEscape
	public String get_4th_yr_dep_per();

	/**
	 * Sets the _4th_yr_dep_per of this vehicle_ catalogue.
	 *
	 * @param _4th_yr_dep_per the _4th_yr_dep_per of this vehicle_ catalogue
	 */
	public void set_4th_yr_dep_per(String _4th_yr_dep_per);

	/**
	 * Returns the _5th_yr_dep_per of this vehicle_ catalogue.
	 *
	 * @return the _5th_yr_dep_per of this vehicle_ catalogue
	 */
	@AutoEscape
	public String get_5th_yr_dep_per();

	/**
	 * Sets the _5th_yr_dep_per of this vehicle_ catalogue.
	 *
	 * @param _5th_yr_dep_per the _5th_yr_dep_per of this vehicle_ catalogue
	 */
	public void set_5th_yr_dep_per(String _5th_yr_dep_per);

	/**
	 * Returns the _6th_yr_dep_per of this vehicle_ catalogue.
	 *
	 * @return the _6th_yr_dep_per of this vehicle_ catalogue
	 */
	@AutoEscape
	public String get_6th_yr_dep_per();

	/**
	 * Sets the _6th_yr_dep_per of this vehicle_ catalogue.
	 *
	 * @param _6th_yr_dep_per the _6th_yr_dep_per of this vehicle_ catalogue
	 */
	public void set_6th_yr_dep_per(String _6th_yr_dep_per);

	/**
	 * Returns the _7th_yr_dep_per of this vehicle_ catalogue.
	 *
	 * @return the _7th_yr_dep_per of this vehicle_ catalogue
	 */
	@AutoEscape
	public String get_7th_yr_dep_per();

	/**
	 * Sets the _7th_yr_dep_per of this vehicle_ catalogue.
	 *
	 * @param _7th_yr_dep_per the _7th_yr_dep_per of this vehicle_ catalogue
	 */
	public void set_7th_yr_dep_per(String _7th_yr_dep_per);

	/**
	 * Returns the _8th_yr_dep_per of this vehicle_ catalogue.
	 *
	 * @return the _8th_yr_dep_per of this vehicle_ catalogue
	 */
	@AutoEscape
	public String get_8th_yr_dep_per();

	/**
	 * Sets the _8th_yr_dep_per of this vehicle_ catalogue.
	 *
	 * @param _8th_yr_dep_per the _8th_yr_dep_per of this vehicle_ catalogue
	 */
	public void set_8th_yr_dep_per(String _8th_yr_dep_per);

	/**
	 * Returns the _9th_yr_dep_per of this vehicle_ catalogue.
	 *
	 * @return the _9th_yr_dep_per of this vehicle_ catalogue
	 */
	@AutoEscape
	public String get_9th_yr_dep_per();

	/**
	 * Sets the _9th_yr_dep_per of this vehicle_ catalogue.
	 *
	 * @param _9th_yr_dep_per the _9th_yr_dep_per of this vehicle_ catalogue
	 */
	public void set_9th_yr_dep_per(String _9th_yr_dep_per);

	/**
	 * Returns the _10th_yr_dep_per of this vehicle_ catalogue.
	 *
	 * @return the _10th_yr_dep_per of this vehicle_ catalogue
	 */
	@AutoEscape
	public String get_10th_yr_dep_per();

	/**
	 * Sets the _10th_yr_dep_per of this vehicle_ catalogue.
	 *
	 * @param _10th_yr_dep_per the _10th_yr_dep_per of this vehicle_ catalogue
	 */
	public void set_10th_yr_dep_per(String _10th_yr_dep_per);

	/**
	 * Returns the _11th_yr_dep_per of this vehicle_ catalogue.
	 *
	 * @return the _11th_yr_dep_per of this vehicle_ catalogue
	 */
	@AutoEscape
	public String get_11th_yr_dep_per();

	/**
	 * Sets the _11th_yr_dep_per of this vehicle_ catalogue.
	 *
	 * @param _11th_yr_dep_per the _11th_yr_dep_per of this vehicle_ catalogue
	 */
	public void set_11th_yr_dep_per(String _11th_yr_dep_per);

	/**
	 * Returns the _12th_yr_dep_per of this vehicle_ catalogue.
	 *
	 * @return the _12th_yr_dep_per of this vehicle_ catalogue
	 */
	@AutoEscape
	public String get_12th_yr_dep_per();

	/**
	 * Sets the _12th_yr_dep_per of this vehicle_ catalogue.
	 *
	 * @param _12th_yr_dep_per the _12th_yr_dep_per of this vehicle_ catalogue
	 */
	public void set_12th_yr_dep_per(String _12th_yr_dep_per);

	/**
	 * Returns the _13th_yr_dep_per of this vehicle_ catalogue.
	 *
	 * @return the _13th_yr_dep_per of this vehicle_ catalogue
	 */
	@AutoEscape
	public String get_13th_yr_dep_per();

	/**
	 * Sets the _13th_yr_dep_per of this vehicle_ catalogue.
	 *
	 * @param _13th_yr_dep_per the _13th_yr_dep_per of this vehicle_ catalogue
	 */
	public void set_13th_yr_dep_per(String _13th_yr_dep_per);

	/**
	 * Returns the _14th_yr_dep_per of this vehicle_ catalogue.
	 *
	 * @return the _14th_yr_dep_per of this vehicle_ catalogue
	 */
	@AutoEscape
	public String get_14th_yr_dep_per();

	/**
	 * Sets the _14th_yr_dep_per of this vehicle_ catalogue.
	 *
	 * @param _14th_yr_dep_per the _14th_yr_dep_per of this vehicle_ catalogue
	 */
	public void set_14th_yr_dep_per(String _14th_yr_dep_per);

	/**
	 * Returns the _1st_yr_dep_val of this vehicle_ catalogue.
	 *
	 * @return the _1st_yr_dep_val of this vehicle_ catalogue
	 */
	@AutoEscape
	public String get_1st_yr_dep_val();

	/**
	 * Sets the _1st_yr_dep_val of this vehicle_ catalogue.
	 *
	 * @param _1st_yr_dep_val the _1st_yr_dep_val of this vehicle_ catalogue
	 */
	public void set_1st_yr_dep_val(String _1st_yr_dep_val);

	/**
	 * Returns the _2nd_yr_dep_val of this vehicle_ catalogue.
	 *
	 * @return the _2nd_yr_dep_val of this vehicle_ catalogue
	 */
	@AutoEscape
	public String get_2nd_yr_dep_val();

	/**
	 * Sets the _2nd_yr_dep_val of this vehicle_ catalogue.
	 *
	 * @param _2nd_yr_dep_val the _2nd_yr_dep_val of this vehicle_ catalogue
	 */
	public void set_2nd_yr_dep_val(String _2nd_yr_dep_val);

	/**
	 * Returns the _3rd_yr_dep_val of this vehicle_ catalogue.
	 *
	 * @return the _3rd_yr_dep_val of this vehicle_ catalogue
	 */
	@AutoEscape
	public String get_3rd_yr_dep_val();

	/**
	 * Sets the _3rd_yr_dep_val of this vehicle_ catalogue.
	 *
	 * @param _3rd_yr_dep_val the _3rd_yr_dep_val of this vehicle_ catalogue
	 */
	public void set_3rd_yr_dep_val(String _3rd_yr_dep_val);

	/**
	 * Returns the _4th_yr_dep_val of this vehicle_ catalogue.
	 *
	 * @return the _4th_yr_dep_val of this vehicle_ catalogue
	 */
	@AutoEscape
	public String get_4th_yr_dep_val();

	/**
	 * Sets the _4th_yr_dep_val of this vehicle_ catalogue.
	 *
	 * @param _4th_yr_dep_val the _4th_yr_dep_val of this vehicle_ catalogue
	 */
	public void set_4th_yr_dep_val(String _4th_yr_dep_val);

	/**
	 * Returns the _5th_yr_dep_val of this vehicle_ catalogue.
	 *
	 * @return the _5th_yr_dep_val of this vehicle_ catalogue
	 */
	@AutoEscape
	public String get_5th_yr_dep_val();

	/**
	 * Sets the _5th_yr_dep_val of this vehicle_ catalogue.
	 *
	 * @param _5th_yr_dep_val the _5th_yr_dep_val of this vehicle_ catalogue
	 */
	public void set_5th_yr_dep_val(String _5th_yr_dep_val);

	/**
	 * Returns the _6th_yr_dep_val of this vehicle_ catalogue.
	 *
	 * @return the _6th_yr_dep_val of this vehicle_ catalogue
	 */
	@AutoEscape
	public String get_6th_yr_dep_val();

	/**
	 * Sets the _6th_yr_dep_val of this vehicle_ catalogue.
	 *
	 * @param _6th_yr_dep_val the _6th_yr_dep_val of this vehicle_ catalogue
	 */
	public void set_6th_yr_dep_val(String _6th_yr_dep_val);

	/**
	 * Returns the _7th_yr_dep_val of this vehicle_ catalogue.
	 *
	 * @return the _7th_yr_dep_val of this vehicle_ catalogue
	 */
	@AutoEscape
	public String get_7th_yr_dep_val();

	/**
	 * Sets the _7th_yr_dep_val of this vehicle_ catalogue.
	 *
	 * @param _7th_yr_dep_val the _7th_yr_dep_val of this vehicle_ catalogue
	 */
	public void set_7th_yr_dep_val(String _7th_yr_dep_val);

	/**
	 * Returns the _8th_yr_dep_val of this vehicle_ catalogue.
	 *
	 * @return the _8th_yr_dep_val of this vehicle_ catalogue
	 */
	@AutoEscape
	public String get_8th_yr_dep_val();

	/**
	 * Sets the _8th_yr_dep_val of this vehicle_ catalogue.
	 *
	 * @param _8th_yr_dep_val the _8th_yr_dep_val of this vehicle_ catalogue
	 */
	public void set_8th_yr_dep_val(String _8th_yr_dep_val);

	/**
	 * Returns the _9th_yr_dep_val of this vehicle_ catalogue.
	 *
	 * @return the _9th_yr_dep_val of this vehicle_ catalogue
	 */
	@AutoEscape
	public String get_9th_yr_dep_val();

	/**
	 * Sets the _9th_yr_dep_val of this vehicle_ catalogue.
	 *
	 * @param _9th_yr_dep_val the _9th_yr_dep_val of this vehicle_ catalogue
	 */
	public void set_9th_yr_dep_val(String _9th_yr_dep_val);

	/**
	 * Returns the _10th_yr_dep_val of this vehicle_ catalogue.
	 *
	 * @return the _10th_yr_dep_val of this vehicle_ catalogue
	 */
	@AutoEscape
	public String get_10th_yr_dep_val();

	/**
	 * Sets the _10th_yr_dep_val of this vehicle_ catalogue.
	 *
	 * @param _10th_yr_dep_val the _10th_yr_dep_val of this vehicle_ catalogue
	 */
	public void set_10th_yr_dep_val(String _10th_yr_dep_val);

	/**
	 * Returns the _11th_yr_dep_val of this vehicle_ catalogue.
	 *
	 * @return the _11th_yr_dep_val of this vehicle_ catalogue
	 */
	@AutoEscape
	public String get_11th_yr_dep_val();

	/**
	 * Sets the _11th_yr_dep_val of this vehicle_ catalogue.
	 *
	 * @param _11th_yr_dep_val the _11th_yr_dep_val of this vehicle_ catalogue
	 */
	public void set_11th_yr_dep_val(String _11th_yr_dep_val);

	/**
	 * Returns the _12th_yr_dep_val of this vehicle_ catalogue.
	 *
	 * @return the _12th_yr_dep_val of this vehicle_ catalogue
	 */
	@AutoEscape
	public String get_12th_yr_dep_val();

	/**
	 * Sets the _12th_yr_dep_val of this vehicle_ catalogue.
	 *
	 * @param _12th_yr_dep_val the _12th_yr_dep_val of this vehicle_ catalogue
	 */
	public void set_12th_yr_dep_val(String _12th_yr_dep_val);

	/**
	 * Returns the _13th_yr_dep_val of this vehicle_ catalogue.
	 *
	 * @return the _13th_yr_dep_val of this vehicle_ catalogue
	 */
	@AutoEscape
	public String get_13th_yr_dep_val();

	/**
	 * Sets the _13th_yr_dep_val of this vehicle_ catalogue.
	 *
	 * @param _13th_yr_dep_val the _13th_yr_dep_val of this vehicle_ catalogue
	 */
	public void set_13th_yr_dep_val(String _13th_yr_dep_val);

	/**
	 * Returns the _14th_yr_dep_val of this vehicle_ catalogue.
	 *
	 * @return the _14th_yr_dep_val of this vehicle_ catalogue
	 */
	@AutoEscape
	public String get_14th_yr_dep_val();

	/**
	 * Sets the _14th_yr_dep_val of this vehicle_ catalogue.
	 *
	 * @param _14th_yr_dep_val the _14th_yr_dep_val of this vehicle_ catalogue
	 */
	public void set_14th_yr_dep_val(String _14th_yr_dep_val);

	/**
	 * Returns the _1st_yr_flat_val of this vehicle_ catalogue.
	 *
	 * @return the _1st_yr_flat_val of this vehicle_ catalogue
	 */
	@AutoEscape
	public String get_1st_yr_flat_val();

	/**
	 * Sets the _1st_yr_flat_val of this vehicle_ catalogue.
	 *
	 * @param _1st_yr_flat_val the _1st_yr_flat_val of this vehicle_ catalogue
	 */
	public void set_1st_yr_flat_val(String _1st_yr_flat_val);

	/**
	 * Returns the _2nd_yr_flat_val of this vehicle_ catalogue.
	 *
	 * @return the _2nd_yr_flat_val of this vehicle_ catalogue
	 */
	@AutoEscape
	public String get_2nd_yr_flat_val();

	/**
	 * Sets the _2nd_yr_flat_val of this vehicle_ catalogue.
	 *
	 * @param _2nd_yr_flat_val the _2nd_yr_flat_val of this vehicle_ catalogue
	 */
	public void set_2nd_yr_flat_val(String _2nd_yr_flat_val);

	/**
	 * Returns the _3rd_yr_flat_val of this vehicle_ catalogue.
	 *
	 * @return the _3rd_yr_flat_val of this vehicle_ catalogue
	 */
	@AutoEscape
	public String get_3rd_yr_flat_val();

	/**
	 * Sets the _3rd_yr_flat_val of this vehicle_ catalogue.
	 *
	 * @param _3rd_yr_flat_val the _3rd_yr_flat_val of this vehicle_ catalogue
	 */
	public void set_3rd_yr_flat_val(String _3rd_yr_flat_val);

	/**
	 * Returns the _4th_yr_flat_val of this vehicle_ catalogue.
	 *
	 * @return the _4th_yr_flat_val of this vehicle_ catalogue
	 */
	@AutoEscape
	public String get_4th_yr_flat_val();

	/**
	 * Sets the _4th_yr_flat_val of this vehicle_ catalogue.
	 *
	 * @param _4th_yr_flat_val the _4th_yr_flat_val of this vehicle_ catalogue
	 */
	public void set_4th_yr_flat_val(String _4th_yr_flat_val);

	/**
	 * Returns the _5th_yr_flat_val of this vehicle_ catalogue.
	 *
	 * @return the _5th_yr_flat_val of this vehicle_ catalogue
	 */
	@AutoEscape
	public String get_5th_yr_flat_val();

	/**
	 * Sets the _5th_yr_flat_val of this vehicle_ catalogue.
	 *
	 * @param _5th_yr_flat_val the _5th_yr_flat_val of this vehicle_ catalogue
	 */
	public void set_5th_yr_flat_val(String _5th_yr_flat_val);

	/**
	 * Returns the _6th_yr_flat_val of this vehicle_ catalogue.
	 *
	 * @return the _6th_yr_flat_val of this vehicle_ catalogue
	 */
	@AutoEscape
	public String get_6th_yr_flat_val();

	/**
	 * Sets the _6th_yr_flat_val of this vehicle_ catalogue.
	 *
	 * @param _6th_yr_flat_val the _6th_yr_flat_val of this vehicle_ catalogue
	 */
	public void set_6th_yr_flat_val(String _6th_yr_flat_val);

	/**
	 * Returns the _7th_yr_flat_val of this vehicle_ catalogue.
	 *
	 * @return the _7th_yr_flat_val of this vehicle_ catalogue
	 */
	@AutoEscape
	public String get_7th_yr_flat_val();

	/**
	 * Sets the _7th_yr_flat_val of this vehicle_ catalogue.
	 *
	 * @param _7th_yr_flat_val the _7th_yr_flat_val of this vehicle_ catalogue
	 */
	public void set_7th_yr_flat_val(String _7th_yr_flat_val);

	/**
	 * Returns the _8th_yr_flat_val of this vehicle_ catalogue.
	 *
	 * @return the _8th_yr_flat_val of this vehicle_ catalogue
	 */
	@AutoEscape
	public String get_8th_yr_flat_val();

	/**
	 * Sets the _8th_yr_flat_val of this vehicle_ catalogue.
	 *
	 * @param _8th_yr_flat_val the _8th_yr_flat_val of this vehicle_ catalogue
	 */
	public void set_8th_yr_flat_val(String _8th_yr_flat_val);

	/**
	 * Returns the _9th_yr_flat_val of this vehicle_ catalogue.
	 *
	 * @return the _9th_yr_flat_val of this vehicle_ catalogue
	 */
	@AutoEscape
	public String get_9th_yr_flat_val();

	/**
	 * Sets the _9th_yr_flat_val of this vehicle_ catalogue.
	 *
	 * @param _9th_yr_flat_val the _9th_yr_flat_val of this vehicle_ catalogue
	 */
	public void set_9th_yr_flat_val(String _9th_yr_flat_val);

	/**
	 * Returns the _10th_yr_flat_val of this vehicle_ catalogue.
	 *
	 * @return the _10th_yr_flat_val of this vehicle_ catalogue
	 */
	@AutoEscape
	public String get_10th_yr_flat_val();

	/**
	 * Sets the _10th_yr_flat_val of this vehicle_ catalogue.
	 *
	 * @param _10th_yr_flat_val the _10th_yr_flat_val of this vehicle_ catalogue
	 */
	public void set_10th_yr_flat_val(String _10th_yr_flat_val);

	/**
	 * Returns the _11th_yr_flat_val of this vehicle_ catalogue.
	 *
	 * @return the _11th_yr_flat_val of this vehicle_ catalogue
	 */
	@AutoEscape
	public String get_11th_yr_flat_val();

	/**
	 * Sets the _11th_yr_flat_val of this vehicle_ catalogue.
	 *
	 * @param _11th_yr_flat_val the _11th_yr_flat_val of this vehicle_ catalogue
	 */
	public void set_11th_yr_flat_val(String _11th_yr_flat_val);

	/**
	 * Returns the _12th_yr_flat_val of this vehicle_ catalogue.
	 *
	 * @return the _12th_yr_flat_val of this vehicle_ catalogue
	 */
	@AutoEscape
	public String get_12th_yr_flat_val();

	/**
	 * Sets the _12th_yr_flat_val of this vehicle_ catalogue.
	 *
	 * @param _12th_yr_flat_val the _12th_yr_flat_val of this vehicle_ catalogue
	 */
	public void set_12th_yr_flat_val(String _12th_yr_flat_val);

	/**
	 * Returns the _13th_yr_flat_val of this vehicle_ catalogue.
	 *
	 * @return the _13th_yr_flat_val of this vehicle_ catalogue
	 */
	@AutoEscape
	public String get_13th_yr_flat_val();

	/**
	 * Sets the _13th_yr_flat_val of this vehicle_ catalogue.
	 *
	 * @param _13th_yr_flat_val the _13th_yr_flat_val of this vehicle_ catalogue
	 */
	public void set_13th_yr_flat_val(String _13th_yr_flat_val);

	/**
	 * Returns the _14th_yr_flat_val of this vehicle_ catalogue.
	 *
	 * @return the _14th_yr_flat_val of this vehicle_ catalogue
	 */
	@AutoEscape
	public String get_14th_yr_flat_val();

	/**
	 * Sets the _14th_yr_flat_val of this vehicle_ catalogue.
	 *
	 * @param _14th_yr_flat_val the _14th_yr_flat_val of this vehicle_ catalogue
	 */
	public void set_14th_yr_flat_val(String _14th_yr_flat_val);

	/**
	 * Returns the default_flag of this vehicle_ catalogue.
	 *
	 * @return the default_flag of this vehicle_ catalogue
	 */
	@AutoEscape
	public String getDefault_flag();

	/**
	 * Sets the default_flag of this vehicle_ catalogue.
	 *
	 * @param default_flag the default_flag of this vehicle_ catalogue
	 */
	public void setDefault_flag(String default_flag);

	/**
	 * Returns the country_name of this vehicle_ catalogue.
	 *
	 * @return the country_name of this vehicle_ catalogue
	 */
	@AutoEscape
	public String getCountry_name();

	/**
	 * Sets the country_name of this vehicle_ catalogue.
	 *
	 * @param country_name the country_name of this vehicle_ catalogue
	 */
	public void setCountry_name(String country_name);

	/**
	 * Returns the enddate of this vehicle_ catalogue.
	 *
	 * @return the enddate of this vehicle_ catalogue
	 */
	@AutoEscape
	public String getEnddate();

	/**
	 * Sets the enddate of this vehicle_ catalogue.
	 *
	 * @param enddate the enddate of this vehicle_ catalogue
	 */
	public void setEnddate(String enddate);

	/**
	 * Returns the order_sequence of this vehicle_ catalogue.
	 *
	 * @return the order_sequence of this vehicle_ catalogue
	 */
	@AutoEscape
	public String getOrder_sequence();

	/**
	 * Sets the order_sequence of this vehicle_ catalogue.
	 *
	 * @param order_sequence the order_sequence of this vehicle_ catalogue
	 */
	public void setOrder_sequence(String order_sequence);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Vehicle_Catalogue vehicle_Catalogue);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Vehicle_Catalogue> toCacheModel();

	@Override
	public Vehicle_Catalogue toEscapedModel();

	@Override
	public Vehicle_Catalogue toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}