/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.axa.glf.masterdata.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.axa.glf.masterdata.model.Vehicle_Catalogue;
import com.axa.glf.masterdata.service.Vehicle_CatalogueLocalServiceUtil;

/**
 * The extended model base implementation for the Vehicle_Catalogue service. Represents a row in the &quot;glf_Vehicle_Catalogue&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Vehicle_CatalogueImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Vehicle_CatalogueImpl
 * @see Vehicle_Catalogue
 * @generated
 */
@ProviderType
public abstract class Vehicle_CatalogueBaseImpl
	extends Vehicle_CatalogueModelImpl implements Vehicle_Catalogue {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a vehicle_ catalogue model instance should use the {@link Vehicle_Catalogue} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			Vehicle_CatalogueLocalServiceUtil.addVehicle_Catalogue(this);
		}
		else {
			Vehicle_CatalogueLocalServiceUtil.updateVehicle_Catalogue(this);
		}
	}
}